### PR TITLE
refactor: migrate from gg drive to s3

### PR DESCRIPTION
**Pull request by dukenguyenxyz**
This PR:
- Resolves issue #2 

@stakach, please review PR #3 before reviewing this one

### CODE REVIEW

**Review by stakach — APPROVED** [review]
LGTM - if you want to perform end-to-end testing against S3, you can add secret ENV vars to travis

**Comment by stakach** [comment]
Do the specs work on your local machine?

**Comment by dukenguyenxyz** [comment]
Like in the comments I mentioned in https://github.com/PlaceOS/wallet_api/pull/3 I'd have to webmock in a hacky way first since some of the HTTP calls are made from the shard. I haven't done E2E testing on my local machine, I simply followed the code from the shard you posted.

**Review by stakach — APPROVED** [review]
LGTM

**Pull request merged**
